### ISSUE TITLE
DDR3 Controller Library?

### ISSUE THREAD

**Issue by rajat-agarwal-** [B-Lang-org/bsc-contrib#1]
Is there a DDR3Controller Library in the original licensed BSC version.?
If yes, then can you please make it available in this git repo as well??

**Comment by quark17** [comment]
Additional libraries that may be useful but are not worth putting in the core (or not sufficiently mature but provided as-is) have been added to a separate repo [bsc-contrib](https://github.com/B-Lang-org/bsc-contrib).  Is this the file you're looking for? [`FPGA/Misc/DDR3.bsc`](https://github.com/B-Lang-org/bsc-contrib/blob/master/Libraries/FPGA/Misc/DDR3.bsv)

**Comment by rajat-agarwal-** [comment]
I don't think so that this is the File. The files are more like https://github.com/sangwoojun/bluespecpcie/tree/master/dram/src the ones in this Repo.

**Comment by quark17** [comment]
I do see that the MIT the lab files (that you pointed me to on IRC) import packages like DDR3Util, DDR3Common, DDR3Controller, and DDR3Sim.  These do not come from Bluespec Inc.  Looking at the GitHub repo that you mention, the files appear to be based on our files (and still have our copyright notice at the top), but they are very different from anything we have (including different names).
